### ISSUE TITLE
The influxdbpropertie class does not work when using @enableautoconfiguration

### ISSUE THREAD

**Issue by kimchanjung** [miwurster/spring-data-influxdb#10]
If you use @EnableAutoConfiguration annotation in spring boot environment, @Validation works before setting property value, and error occurs that the value is not set

If @EnableAutoConfiguration annotation is not used, it works normally

Instead of using the spring-data-influxdb module implementation, you can use the newly created factory implements
We have confirmed that the bean is used after registering it by using InfluxDBProperties class which removed @Validation annotation

**Comment by miwurster** [comment]
Hi @kimchanjung, sorry for the late response. Any chance that you can provide a PR?

**Comment by miwurster** [comment]
Hi @kimchanjung, I tried to reproduce your described behavior. In my case if works totally fine if I use the `@EnableAutoConfiguration` annotation.
Can you maybe provide an example that shows your issue? What are you doing differently than in my [test class](https://github.com/miwurster/spring-data-influxdb/blob/master/src/test/java/org/springframework/data/influxdb/Application.java)?
Thanks,
Michael

**Comment by miwurster** [comment]
Closing this issue.
