### ISSUE TITLE
Do you support bulk submission?

### ISSUE THREAD

**Issue by www6223166** [miwurster/spring-data-influxdb#15]
Do you support bulk submission?

**Comment by miwurster** [comment]
The default template is implemented to write `BatchPoints` to Influx, see https://github.com/miwurster/spring-data-influxdb/blob/master/src/main/java/org/springframework/data/influxdb/InfluxDBTemplate.java#L74.

**Comment by www6223166** [comment]
OK,thx    o(∩_∩)o
