### ISSUE TITLE
question on your from t page example

### ISSUE THREAD

**Issue by EvilJinious1** [miwurster/spring-data-influxdb#2]
You reference a class called Measurements in your Readme.md example.  

I did not find this class in either your source or the influxdb-java source.  This was just a for instance?

Thanks

**Comment by miwurster** [comment]
Hi,

yes, that's just an example. You can use your own measurement/metric object and supply an appropriate converter implementation for it.

Btw, in version 1.3 (published a couple of minutes ago) I tried to simplify the usage of the library. Please check the source code example inside the `test` space.

Cheers
Michael

**Comment by miwurster** [comment]
Hey, 

I released a new version (1.4) where I added a default template implementation (DefaultInfluxDBTemplate). You could use this right away if you are just dealing with Point objects from `influxdb-java`.

Hope this helps in some way.

Cheers
Michael
