### ISSUE TITLE
Does this project configure the connection pool for the influxdb

### ISSUE THREAD

**Issue by ZhenChen008** [miwurster/spring-data-influxdb#24]
Hello，
   I'm also integrating springboot and influxDB, but I can't find available**connection pool** !
May I ask is this project configure the connection pool for the influxDB?
**If yes, could you please show what connection pool is used?**

**Comment by miwurster** [comment]
Hi, no at the moment there is no connection pool in use. The class [InfluxDBConnectionFactory](https://github.com/miwurster/spring-data-influxdb/blob/master/src/main/java/org/springframework/data/influxdb/InfluxDBConnectionFactory.java) creates a connection object of type `InfluxDB` from the actual InfluxDB library. AFAIK this is an abstraction over a HTTP connection to the InfluxDB API. You should check their implementation whether they use some pooling or whether it's just a client for a stateless connection to their API.

**Comment by ZhenChen008** [comment]
> 嗨，目前没有使用连接池。[类 InfluxDBConnectionFactory](https://github.com/miwurster/spring-data-influxdb/blob/master/src/main/java/org/springframework/data/influxdb/InfluxDBConnectionFactory.java) 从实际的 InfluxDB 库创建一个类型的连接对象。AFAIK 这是通过 HTTP 连接到 InfluxDB API 的抽象。您应该检查他们的实现是否使用某些池化，或者它是否只是与其 API 建立无状态连接的客户端。`InfluxDB`

OK ，get it ,thanks!
It seems that OkHTTP  has a connection pool ,such as [these](https://github.com/search?o=desc&q=influxdb+connection+pool++language%3Ajava&s=&type=Code)
