### ISSUE TITLE
Support for batching functionality of influxdb-java

### ISSUE THREAD

**Issue by r0ann3l** [miwurster/spring-data-influxdb#5]
This module should provide a way to enable the batching functionality of influxdb-java and gzip compression as well. It can be through configuration.

**Comment by miwurster** [comment]
Great idea, any chance that you could provide a pull request?

**Comment by miwurster** [comment]
Feature implemented with the latest [release](https://github.com/miwurster/spring-data-influxdb/releases/tag/spring-data-influxdb-1.6).
