### ISSUE TITLE
group by select problem

### ISSUE THREAD

**Issue by hrecho** [miwurster/spring-data-influxdb#6]
Hi

this 
`select last(*) from occupancy group by psid`

returns only one record
even though in console i see two records

my code ...
```
		String queryString = "select last(*) from occupancy group by psid";
		QueryResult queryResult = influxDBTemplate.getConnection().query(
				new Query(queryString, "parkdots"));
		queryResult.toString();
```
is the problem in front of the monitor or inside the box ?

**Comment by miwurster** [comment]
Hey, sorry for the late response... I tried to reproduce this in my test environment (based on the `docker-compose.yml` file) and added an example to [`Application.java`](https://github.com/miwurster/spring-data-influxdb/blob/master/src/test/java/org/springframework/data/influxdb/Application.java). In both, the application and the console, I only get one record with my test data.
Can you show me what kind of data do you publish to Influx? At least with my very very simple example I cannot reproduce this behavior...

**Comment by hrecho** [comment]
this resulted from my bad influxdb knowledge
i was mixin fields and tags probably
now i still dont really understand the limitations but there should be some
i mean
one can group via tags and not via fields
or in some cases (if aggregating) one can display fields but not tags (this was probably the case)
tags and fields play different role in influx query
i solved this prob when i changed recording via fields and started using tags
still i must appologise as this was a result of my poor knowledge of the technology
i forgot the thread and now i wasted your time
soooory

**Comment by miwurster** [comment]
No worries, isn't a big deal... ;-)
